_target_: modules.io.load.loaders.HypergraphLoader

# Data definition
parameters:
  data_domain: hypergraph
  data_type: coauthorship
  data_name: Cora
  data_dir: ${oc.env:PROJECT_ROOT}/datasets/${parameters.data_domain}/${parameters.data_type}/${parameters.data_name}
  data_split_dir: ${oc.env:PROJECT_ROOT}/datasets/data_splits/${parameters.data_name}

  # Dataset parameters
  num_features: 1433
  num_classes: 7
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: node
  split_type: k-fold 
  k: 10 # Number of folds
  data_seed: 0 # Fold number
