_target_: modules.io.load.loaders.GraphLoader

# Data definition
parameters:
  data_domain: graph
  data_type: TUDataset
  data_name: IMDB-BINARY
  data_dir: ${oc.env:PROJECT_ROOT}/datasets/${parameters.data_domain}/${parameters.data_type}
  data_split_dir: ${oc.env:PROJECT_ROOT}/datasets/data_splits/${parameters.data_name}

  # Dataset parameters
  num_features: 136 # In IMDB-BINARY dataset, num_features is equal to maximum node degree among all graphs +1
  max_node_degree: 135
  max_x_1_degree: 135
  num_classes: 2
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: graph
  split_type: k-fold 
  k: 10 # Number of folds
  data_seed: 0 # Fold number



