_target_: modules.io.load.loaders.SimplicialLoader

# Data definition
parameters:
  data_domain: simplicial
  data_type: social
  data_name: KarateClub
  data_dir: ${oc.env:PROJECT_ROOT}/datasets/${parameters.data_domain}/${parameters.data_type}/${parameters.data_name}
  data_split_dir: ${oc.env:PROJECT_ROOT}/datasets/data_splits/${parameters.data_name}

  # Dataset parameters
  num_features: 2
  num_classes: 2
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: node
  data_seed: 0
