_target_: modules.io.load.loaders.GraphLoader

# Data definition
parameters:
  data_domain: graph
  data_type: TUDataset
  data_name: MUTAG
  data_dir: ${oc.env:PROJECT_ROOT}/datasets/${parameters.data_domain}/${parameters.data_type}
  data_split_dir: ${oc.env:PROJECT_ROOT}/datasets/data_splits/${parameters.data_name}

  # Dataset parameters
  num_features:
    - 7 # initial node features
    - 4 # initial edge features
  num_classes: 2
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: graph
  split_type: k-fold 
  k: 10 # Number of folds
  data_seed: 0 # Fold number

  # Lifting parameters
  max_dim_if_lifted: 2
  preserve_edge_attr_if_lifted: False

