_target_: modules.io.load.loaders.GraphLoader

# Data definition
parameters:
  data_domain: graph
  data_type: TUDataset
  data_name: PROTEINS
  data_dir: ${oc.env:PROJECT_ROOT}/datasets/${parameters.data_domain}/${parameters.data_type}
  data_split_dir: ${oc.env:PROJECT_ROOT}/datasets/data_splits/${parameters.data_name}

  # Dataset parameters
  num_features: 3 # here basically I specify the initial num features in PROTEINS at x aka x_0
  num_classes: 2
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: graph
  data_seed: 9
  split_type: 'k-fold' # either k-fold or test
  k: 10 # for k-Fold Cross-Validation



