data_domain: graph
data_type: TUDataset
data_name: REDDIT-BINARY
data_dir: ${oc.env:PROJECT_ROOT}/datasets/${data_domain}/${data_type}
data_split_dir: ${oc.env:PROJECT_ROOT}/datasets/data_splits/${data_name}

# Dataset parameters
num_features: 10
max_node_degree: 3062
# max_x_1_degree: 3062
num_classes: 2
task: classification
loss_type: cross_entropy
monitor_metric: accuracy
task_level: graph
