_target_: modules.io.load.loaders.GraphLoader

# Data definition
parameters:
  data_domain: graph
  data_type: ZINC
  data_name: ZINC
  data_dir: ${oc.env:PROJECT_ROOT}/datasets/${parameters.data_domain}/${parameters.data_type}
  data_split_dir: ${oc.env:PROJECT_ROOT}/datasets/data_splits/${parameters.data_name}

  # Dataset parameters
  num_features: 1 # here basically I specify the initial num features in mutang at x aka x_0
  num_classes: 1
  task: regression
  loss_type: mse
  monitor_metric: mae
  task_level: graph
  data_seed: 0
  split_type: 'fixed' # either k-fold or test
  #k: 10 # for k-Fold Cross-Validation

